In [8]:
import pandas as pd
import numpy as np

In [9]:
train = pd.read_csv('data/train.csv')
cluster_labels = np.load('data_gen/cluster_labels.npy')

In [10]:
train

                   ImageID
0      6119677716839104391
1     14802949761255250525
2     14124813423892560492
3      5482257461254211163
4     10081435122427592003
...                    ...
2616   9060386186086836431
2617   3583815641843563968
2618   2719679196594321269
2619  15043768931442006468
2620   9722418938962263447

[2621 rows x 1 columns]

In [11]:
cluster_labels

array([4, 7, 8, ..., 8, 6, 7], shape=(2621,))

In [12]:
train['cluster'] = cluster_labels
train

                   ImageID  cluster
0      6119677716839104391        4
1     14802949761255250525        7
2     14124813423892560492        8
3      5482257461254211163        8
4     10081435122427592003        8
...                    ...      ...
2616   9060386186086836431        0
2617   3583815641843563968       10
2618   2719679196594321269        8
2619  15043768931442006468        6
2620   9722418938962263447        7

[2621 rows x 2 columns]

In [24]:
train.to_csv('data/train_with_clusters.csv', index=False)

In [18]:
train_clusters = [1, 3, 4, 6, 7, 8]
val_clusters = [0, 2, 5, 9]

In [19]:
train_split = train.query('cluster in @train_clusters')
val_split = train.query('cluster in @val_clusters')

In [20]:
train_split

                   ImageID  cluster
0      6119677716839104391        4
1     14802949761255250525        7
2     14124813423892560492        8
3      5482257461254211163        8
4     10081435122427592003        8
...                    ...      ...
2614   4979313955966070608        8
2615   5565718144312255152        8
2618   2719679196594321269        8
2619  15043768931442006468        6
2620   9722418938962263447        7

[2169 rows x 2 columns]

In [21]:
val_split

                   ImageID  cluster
19     8132759621826780913        5
24    12554066507661484507        2
28    13741566418719621391        5
35    11180598794627341818        2
42     7353008532465742054        5
...                    ...      ...
2550   4056888175875938167        0
2566   6395615772569039770        9
2572  11341394191072214327        0
2573  12475971032595384520        2
2616   9060386186086836431        0

[268 rows x 2 columns]

In [23]:
train_split.to_csv('data/train_split_with_cluster.csv', index=False)
val_split.to_csv('data/val_split_with_cluster.csv', index=False)
train_split['ImageID'].to_csv('data/train_split.csv', index=False)
val_split['ImageID'].to_csv('data/val_split.csv', index=False)